// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVkS-uQcoL3J6m0Ayb-2yR6Tg0uWsu3aE',
    appId: '1:329890456020:web:0b82587d02a126de3c7641',
    messagingSenderId: '329890456020',
    projectId: 'imagetotext-93041',
    authDomain: 'imagetotext-93041.firebaseapp.com',
    storageBucket: 'imagetotext-93041.appspot.com',
    measurementId: 'G-5P1F13SCB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHovJZU2E335S8Q_w9EoUV1SyJWuwDCm8',
    appId: '1:329890456020:android:a2ac2df4279178823c7641',
    messagingSenderId: '329890456020',
    projectId: 'imagetotext-93041',
    storageBucket: 'imagetotext-93041.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDah28neUkUPX9akKRkjmG1hMeva4iWVuE',
    appId: '1:329890456020:ios:9735e379228274393c7641',
    messagingSenderId: '329890456020',
    projectId: 'imagetotext-93041',
    storageBucket: 'imagetotext-93041.appspot.com',
    iosBundleId: 'com.example.imageToText',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDah28neUkUPX9akKRkjmG1hMeva4iWVuE',
    appId: '1:329890456020:ios:7c661980a628dcff3c7641',
    messagingSenderId: '329890456020',
    projectId: 'imagetotext-93041',
    storageBucket: 'imagetotext-93041.appspot.com',
    iosBundleId: 'com.example.imageToText.RunnerTests',
  );
}
